Codehagen/Badget

components/layout/navbar.tsx
Updated the navbar position
closes #7
=> style: updated navbar position

components/layout/sign-in-modal.tsx
- Bug: After signing in the user is not redirected to the dashboard #19
=> fix(auth): Redirect to /dashboard after sign-in

components/accounts/components/mail.tsx
=> fix: accounts resizablepanel in the middle

components/accounts/components/accounts-display.tsx, components/investments/components/accounts-display.tsx
Fixed account and investment title color in darkmode
=> fixed account and investment title color in darkmode

components/investments/components/small-investment-card.tsx
=> added horizontal scrolling on small investment card

components/investments/components/holdings-table.tsx
=> Switched from img element to next Image component

components/layout/main-nav.tsx, components/shared/askai-command.tsx
UI Component for AI / Command Integration, Quick launch function with keyboard shortcut for Search & AI integration.
=> UI Component for AI / Search Integration

app/(dashboard)/dashboard/accounts/page.tsx, app/(dashboard)/dashboard/layout.tsx, app/(dashboard)/dashboard/page.tsx, app/(dashboard)/dashboard/transactions/page.tsx, app/(dashboard2)/dashboard2/layout.tsx, app/(docs)/layout.tsx, components/layout/site-footer.tsx
Minimal setup to be able to preview the dashboard on mobile, further refinement needed inorder to be able to visualize data correctly
=> ui optimizations and mobile support on the dashboard

app/(marketing)/oss-friends/page.tsx
addresses  - #63 
Added new OSS Friends Page
https://github.com/meglerhagen/projectx/assets/78979288/42ae7630-5f3a-4f76-ac66-b28553e7bf66
=> feat: add oss-friends page

app/(marketing)/oss-friends/page.tsx
Apologies for the oversight in the previous pull request #64 . This PR addresses formatting issues that were missed in the initial merge. The changes are focused solely on code formatting improvements.
=> fix formating

components/investments/components/small-investment-card.tsx
importing investment data from data.tsx file and updating the state with useMail hook.
This PR adds the feature.
Fixes #60
Mobile & Desktop Screenshots/Recordings
https://www.loom.com/share/aeebfb84a21846e6bc87f7f2631d20b3?sid=c6b4cb1f-8a6c-4112-ad4b-1c1dabc534a4
Visit to investment dashboard and try clicking on investment cards and see if data changes on right panel.
=> feat: sync data in investment dashboard

turbo.json
Update output paths in turbo.json
=> Update build outputs in turbo.json

apps/www/lib/subscription.ts, apps/www/tsconfig.json
Fixed code style for tsconfig and subscription. Will fix this: https://github.com/meglerhagen/projectx/actions/runs/7657127548
=> fix: tsconfig and subscription code style

README.md
=> Folder based docs tree

apps/www/app/(marketing)/page.tsx, apps/www/app/sitemap.ts, packages/transactional/emails/welcome-email.tsx
Fixes: #107 
There's mention to an email as well, what value should we use instead?
- #107
=> Replace projectx.com domain with vercel domain

README.md
I had a hard time setting up the project because I had to dig around to find what accounts and API keys needed to be created for the project to run. This Update to the Readme makes it very clear what needs to be done.
=> Updates Docs for Setting Project Up

packages/db/src/enum.ts, packages/db/src/index.ts, packages/db/src/queries/index.ts, packages/db/src/schema/account.ts, packages/db/src/schema/category.ts, packages/db/src/schema/institution.ts, packages/db/src/schema/item.ts, packages/db/src/schema/transaction.ts
This PR fixes the feature: #111 .
All that's needed is a `pnpm run db:push`
=> feat(db): refactor db tables

apps/www/app/(dashboard)/dashboard/settings/account/page.tsx, apps/www/app/(dashboard)/dashboard/settings/appearance/page.tsx, apps/www/app/(dashboard)/dashboard/settings/bank-account/page.tsx, apps/www/app/(dashboard)/dashboard/settings/display/page.tsx, apps/www/app/(dashboard)/dashboard/settings/notifications/page.tsx
=> Add meta data(title,description)

apps/www/app/(dashboard)/dashboard/accounts/page.tsx, apps/www/app/(dashboard)/dashboard/categories/page.tsx, apps/www/app/(dashboard)/dashboard/investments/page.tsx, apps/www/app/(dashboard)/dashboard/recurring/page.tsx, apps/www/app/(dashboard)/dashboard/transactions/page.tsx, apps/www/components/accounts/components/accounts-dashboard.tsx, apps/www/components/categories/components/categories-dashboard.tsx, apps/www/components/investments/components/investment-dashboard.tsx, apps/www/components/new-dashboard/components/dashboard-1.tsx, apps/www/components/transactions/components/recurring-dashboard.tsx, apps/www/components/transactions/components/transactions-dashboard.tsx
The default layout for the Transactions, Accounts, Dashboard, Recurring, and Categories dashboards has been updated. The previous default layout values [265, 440, 655] have been changed to [20, 40, 40]. This change was made to improve the initial layout and make it more visually appealing for users.
Fixing a closed issue #42
- [X ] 🙅 no documentation needed
=> feat: update default layout for dashboard panels

apps/www/components/dashboard/feautressection.tsx
This PR fixes #159 issue with gradient being white when using dark mode, by simply replacing this tailwind style: 
`from-white` with `from-background`
Fixes #159 
From this:
To this:
=> fix: bottom gradient on landing page issue when in dark mode

apps/www/components/buttons/AddMiscButton.tsx
- Created a new component called "AddMiscButton" which renders a button to add valuables.
- When the button is clicked, a dialog is opened.
- The dialog contains a form to input the name, purchase date, purchase value, and current value of the valuables.
- Added a calendar component to select the purchase date.
- Added a submit button to add the valuables.
=> ✨ feat: add "Add Valuables" functionality

apps/www/components/investments/components/investment-cards.tsx
This PR fixes the issue #171 
1. Go to dashboard/investments.
2. Under the Accounts section.
3. Hover over the investment card to see the difference.
=> Fixed the issue of text not visible on investment card hover.

README.md
In this PR I have added the steps we can use to setup stripe locally to start the development process.
=> Readme stripe info

apps/www/components/savemoney/components/ai-magic-dashboard.tsx, apps/www/components/savemoney/components/empty-screen.tsx, apps/www/components/savemoney/components/mini-chat.tsx
This PR is related to issue #161 
Features Added:
1. Added state management to showcase the chat suggestions dialogue.
2. Added functionality to change the chat input through examples given in the chat suggestions.
3. Added a subtle animation in the EmptyScreen component to give users visual feedback about the suggestion they are choosing.
1. Go to dashboard/aimagic.
2. Select any of the chat suggestions.
4. If you want, you can alter the input and then click send.
5. Once you send the query, the query will get pushed to the stack of messages.
=> Implemented empty screen component for user guidance.

apps/www/components/categories/components/categories-dashboard.tsx, apps/www/components/categories/components/categories-display.tsx, apps/www/components/categories/components/investment-cards.tsx, apps/www/components/investments/components/investment-dashboard.tsx, apps/www/components/new-dashboard/components/dashboard-1.tsx, apps/www/components/new-dashboard/components/stats.tsx, apps/www/components/new-dashboard/components/top-categories-table.tsx, apps/www/components/recurring/components/categories-display.tsx, apps/www/components/recurring/components/total-balance-card.tsx, apps/www/components/savemoney/components/ai-magic-dashboard.tsx, apps/www/components/transactions/components/recurring-dashboard.tsx
In this PR: 
- I have addressed the issue #180 of double scrolling on dashboard. 
- Applied consistent padding for pages across the app and commented out unused separators.
- Changed the fill color for the bar graph on the dashboard, as black color is not visible properly with dark mode.
=> Fixed double scroll issue along with consistent padding across pages

apps/www/components/buttons/AddRealEstateButton.tsx, packages/validators/package.json, packages/validators/src/realEstate.ts
=> Feat enhanced type safety for Real Estate form

apps/www/app/(marketing)/blog/page.tsx, apps/www/middleware.ts
Blog isn't open for unauthenticated users to fix that and make it public
=> add blog as public route

apps/www/app/(dashboard)/dashboard/settings/layout.tsx
At present there is no way to go back to the dashboard if we are on the settings page. With this PR I have introduced a redirection link on top of the settings page to go back to the dashboard.
=> Redirection link to Dasboard.

apps/www/components/buttons/AddAssetButton.tsx, apps/www/components/forms/account-form/car-fields.tsx, apps/www/components/forms/account-form/common-account-fields.tsx, apps/www/components/forms/account-form/crypto-fields.tsx, apps/www/components/forms/account-form/index.tsx, apps/www/components/forms/account-form/input-fields.tsx, apps/www/components/forms/account-form/investment-fields.tsx, apps/www/components/forms/account-form/misc-fields.tsx, apps/www/components/forms/account-form/real-estate-fields.tsx, apps/www/components/modals/add-asset-flow/components/account-type-selection.tsx, apps/www/components/modals/add-asset-flow/components/footer.tsx, apps/www/components/modals/add-asset-flow/components/header-controls.tsx, apps/www/components/modals/add-asset-flow/index.tsx, apps/www/components/new-dashboard/components/dashboard-1.tsx, apps/www/components/ui/dialog.tsx, apps/www/hooks/use-flow-control.ts, apps/www/hooks/use-flow-modal-state.ts, apps/www/package.json, pnpm-lock.yaml
=> Dynamic dialogs based on selections

apps/www/components/forms/account-form/car-fields.tsx, apps/www/components/forms/account-form/common-account-fields.tsx, apps/www/components/forms/account-form/crypto-fields.tsx, apps/www/components/forms/account-form/input-fields.tsx, apps/www/components/forms/account-form/investment-fields.tsx, apps/www/components/forms/account-form/misc-fields.tsx, apps/www/components/forms/account-form/name-field.tsx, apps/www/components/forms/account-form/real-estate-fields.tsx, apps/www/components/modals/add-asset-flow/index.tsx, apps/www/hooks/use-flow-modal-state.ts, apps/www/lib/utils.ts
=> feat: Number Formatting and UI Consistency Enhancement

apps/www/components/new-dashboard/components/dashboard-1.tsx, apps/www/components/new-dashboard/components/nav.tsx, apps/www/config/dashboard.ts, apps/www/config/property.ts
=> Clearnup #194

apps/www/app/(dashboard)/(workspaceId)/error.tsx, apps/www/components/dashboard/feautressection.tsx, apps/www/next.config.js
=> Replace Homepage with dashboard screenshot

apps/www/app/(dashboard)/(workspaceId)/error.tsx
=> Error-ui improvement

packages/api/src/router/stripe.ts
=> asap fix for denerio in stripe.ts

apps/www/components/forms/account-form/account-fields.tsx, apps/www/components/forms/account-form/asset-fields.tsx, apps/www/components/forms/account-form/investment-fields.tsx, apps/www/components/forms/account-form/real-estate-fields.tsx, packages/validators/src/index.ts
Add a space between numbers for every 3 digits and also support decimal values.
Fixes #244 
https://github.com/projectx-codehagen/Badget/assets/22556726/45bff131-c942-4503-9107-47fb7ab05f64
1. Go to /dashboard
2. Click on Add Asset
3. Click on "Account" / "Asset"
=> feat: Spacing between numbers in modal

apps/www/src/actions/calculate-suggested-budget.ts, apps/www/src/actions/create-budget.ts, apps/www/src/actions/get-categories-review.ts, apps/www/src/actions/get-categories.ts, apps/www/src/actions/get-transactions-for-category.ts, apps/www/src/actions/get-user-budget.ts, apps/www/src/actions/get-user-categories.ts, apps/www/src/actions/update-budget.ts, apps/www/src/app/(dashboard)/dashboard/categories/page.tsx, apps/www/src/app/(dashboard)/dashboard/page.tsx, apps/www/src/components/banking/BankingDashboardTable.tsx, apps/www/src/components/categories/BudgetCreationDialog.tsx, apps/www/src/components/categories/CategoriesContent.tsx, apps/www/src/components/categories/CategoriesDropdownMenu.tsx, apps/www/src/components/categories/CategorySpendingChart.tsx, apps/www/src/components/categories/RegularCategoriesTable.tsx, apps/www/src/components/categories/TransactionTable.tsx, apps/www/src/components/charts/CategoryChart.tsx, apps/www/src/components/shared/icons.tsx, apps/www/src/components/tables/TransactionsToReview.tsx, apps/www/src/components/tables/transactions/components/review-transactions-table.tsx, apps/www/src/config/dashboard.ts, packages/db/prisma/schema.prisma
=> 263 feature categories

package.json, pnpm-lock.yaml, src/app/(main)/categories/page.tsx, src/app/(main)/dashboard/page.tsx, src/app/(main)/liabilities/page.tsx, src/app/(main)/savings/page.tsx, src/app/(main)/template/page.tsx, src/app/globals.css, src/components/categories/budget-summary.tsx, src/components/categories/category-chart.tsx, src/components/categories/category-list.tsx, src/components/categories/category-trends.tsx, src/components/categories/edit-budget.tsx, src/components/categories/recent-transactions.tsx, src/components/liabilities/add-liability.tsx, src/components/liabilities/liability-allocation.tsx, src/components/liabilities/liability-cards.tsx, src/components/liabilities/liability-table.tsx, src/components/liabilities/total-liabilities-chart.tsx, src/components/nav-user.tsx, src/components/savings/savings-goals.tsx, src/components/savings/savings-overview.tsx, src/components/savings/savings-recommendations.tsx, src/components/savings/savings-tips.tsx, src/components/ui/progress.tsx
Done with initial UI for Badget after Rewrok 🧑‍🎨
=> Done with components 🪄✨
